# Generated by Django 3.1.5 on 2021-05-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='ordererd_date',
            new_name='ordered_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='descriptiom',
            new_name='description',
        ),
    ]
